version: '3'
services:
  backend:
    build: ./back
    ports:
      - "8000:8000"
  frontend:
    build: ./front/review-classification-app
    ports:
      - "3000:3000"
    depends_on:
      - backend